### ISSUE TITLE
Switch JAX-RS API dep to jakarta.ws.rs-api

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo#153]
This is the new dependency name after Java EE was transferred to Eclipse.

**Comment by berezovskyi** [comment]
We should consider a set of parallel modules in Lyo to support both. Rationale:

- Need to switch in order to be able to use Tomcat 10 or Jetty 11, they no longer support the old APIs.
- Eclipse Microprofile introduces a number of specs needed for production and cloud-native use of OSLC servers, we'd like to adopt them. They are baselined on the Jakarta EE (new namespace).

**Comment by danlz** [comment]
I second this, the sooner the better :)

**Comment by jhemm2** [comment]
+1 for this. This will make lyo usable in springboot 3 projects, using java17 and JakartaEE9

**Comment by danlz** [comment]
We are almost at the point of abandoning Lyo  and do the stuff ourselves.

**Comment by jhemm2** [comment]
I am just trying to implement that change and to create a PR, so hopefully it can be integrated early in an upcoming release?

**Comment by Jad-el-khoury** [comment]
> I am just trying to implement that change and to create a PR, so hopefully it can be integrated early in an upcoming release?

Contributions are very welcome. What makes an open source project successful is when users also contribute.
@jhemm2! Feel free to push a PR early, and maybe I can even help out.

**Comment by jhemm2** [comment]
Lots of changes, unfortunately the editorconfig did not work very well so xml files got some reformatting :/
https://github.com/eclipse/lyo/pull/500

**Comment by Jad-el-khoury** [comment]
Great @jhemm2 ! A big change so need to think on how we process this.
Any reason #500 is closed?

**Comment by jhemm2** [comment]
First time I am trying to to contribute, and I saw some build was failing so I decided to delete the PR and validate the changes again.
Guess I need some support: Is it the right way to fork the repo, do the changes, then to create a PR into master?
Also on my local machine the build was successful, I need to check what is missing

**Comment by Jad-el-khoury** [comment]
Can you see the results of the actions on https://github.com/eclipse/lyo/actions ? Not sure if you have access..
I can see the maven error, and just want to make sure you can also see it.

When it comes to contribution, doing a PR is very fine.
Please see these guidelines. https://github.com/eclipse/lyo/blob/master/CONTRIBUTING.md

Most importantly, are you an Eclipse Contributor?

**Comment by berezovskyi** [comment]
@Jad-el-khoury I replied on #500

**Comment by danlz-propstep** [comment]
What's the plan for releasing the 6.0.0 aka Jakarta version?

**Comment by danlz** [comment]
What is the plan for releasing the 6.0.0 aka Jakarta version?
