### ISSUE TITLE
oslc-wink depends on Spring

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo#23]
Why?

**Comment by jamsden** [comment]
Not sure, maybe to provide OAuth2 authentication for non-web clients?

**Comment by jadelkhoury** [comment]
@berezovskyi Can you please provide more information? This statement "oslc-wink depends on Spring" doesn't tell me much. #fakenews maybe?

**Comment by berezovskyi** [comment]
General note: if I don't @ mention you, it's an issue I noted to look into when I have time while working on something else and not wishing to get distracted. If I want an answer from you, I will nag you (I don't think I need to convince you of that :D). I recommend you adjust your notifications maybe? I don't want to assign myself because I try to keep list of assigned issues the ones I planning to work on soon.

**Comment by berezovskyi** [comment]
About the issue: I saw Snyk suggested security fixes for Spring on the Lyo repo and I was dumbfounded by that.

**Comment by jadelkhoury** [comment]
You've convinced me. I will adjust notifications.
But a general note back at you: This list of issues will have to make sense to us in x months/years from now. Otherwise, we will not be able to differentiate mental notes from real issues. 
Suggestion: How about a label "Andrii mental note" :-)

**Comment by jadelkhoury** [comment]
Actually, I don't want to unwatch. Becauase I want to know if some "real" issues are added.
Can I unwatch from specific people? :-)

**Comment by berezovskyi** [comment]
Ok, I will try to be more descriptive in the future and add some tag

**Comment by jadelkhoury** [comment]
Let me share my perspective: I did the migration from wink to Jaxrs2.0 (Jersey). of course I will think this is relevant, unless you tell me otherwise. (Normally, I do try to ingore many notifications)

**Comment by berezovskyi** [comment]
[eclipse:lyo:server:oslc4j-wink:pom.xml | Snyk.pdf](https://github.com/eclipse/lyo/files/5643629/eclipse.lyo.server.oslc4j-wink.pom.xml.Snyk.pdf) detailed report

**Comment by berezovskyi** [comment]
True, I didn't think of it in that way, Jad. Please see the report linked above. I know as little as you do, but I would like to either update those deps or get rid of them.

**Comment by jadelkhoury** [comment]
excellent. As soon as I see the word "snyk" I know that I can ignore it :-)

**Comment by berezovskyi** [comment]
oslc-wink was removed from Lyo 5.0
