### ISSUE TITLE
OslcClient.lookupServiceProviderUrl doesn't check for authentication failure

### ISSUE THREAD

**Issue by jamsden** [eclipse/lyo#31]
It simply proceeds to attempt to consume the text/html entity response body for the authentication failure as RDF/XML which produces an inappropriate and unfriendly error message that doesn't mention authentication failure.

**Comment by berezovskyi** [comment]
https://github.com/eclipse/lyo/blob/master/client/oslc-client/src/main/java/org/eclipse/lyo/client/RootServicesHelper.java#L257 now takes care of what you were after. We will track my proposal in #32
