### ISSUE TITLE
Double Encoding for the space in OSLCQueryParameter

### ISSUE THREAD

**Issue by Palrajjayaraj** [eclipse/lyo#38]
While setting the where clause, using setWhere API, in a ‘OslcQueryParameters’, the string is being encoded. When the queryURL is being constructed in the Constructor OslcQuery, the where clause String is encoded again. so, whenever there is a space (' ') in the where clause, it is being encoded to '+' in the setWhere API. and this '+' is encoded to %2B in the JerseyUriBuilder._build API, during the OslcQuery constructor.
eg. OslcQueryParameters.setWhere(“oslc:shortId in [100,101]”) results in the final where clause 
"oslc.where=oslc%3AshortId%2Bin%2B%5B100%2C101%5D".

The discussion with Jad regarding the issue is located in the below topic in forum:
https://forum.open-services.net/t/double-encoding-for-the-space-in-oslcqueryparamater/395/4

**Comment by berezovskyi** [comment]
Fixed by Jad in https://github.com/eclipse/lyo.client/commit/7d472b2043140014377ba034a98fa8bdf3e55077
