### ISSUE TITLE
Test IECMSample against RTC configured for JAS

### ISSUE THREAD

**Issue by jamsden** [eclipse/lyo#39]
This will test if OslcClient apps can use OpenIDConnect.

**Comment by berezovskyi** [comment]
I think I fixed a JAS connection bug in https://github.com/eclipse/lyo/commit/d8e2e4bc13e18ffad72af1ffa09bdd7cff0f86da and https://github.com/OSLC/lyo-samples/commit/49ee279b51a5117e7b45cbcab12002a299e5c5db, please try again.

**Comment by berezovskyi** [comment]
The Lyo Client bug should be fixed, closing this issue as there are ELM sample code in this repo.
