### ISSUE TITLE
NOTICE file still states the EPL-1.0 as applicable license

### ISSUE THREAD

**Issue by stefan-hdt** [eclipse/lyo#397]
I just saw that the NOTICE file in this repository still states the EPL-1.0 and the BSD-3-Clause both as applicable licenses. According to https://github.com/eclipse/lyo/blob/master/LICENSE and the the source code, the EPL-2.0 and the BSD-3-Clause are now applicable.

You might consider adapting the NOTICE file since it might confuse people.

Kind regards,

Stefan

**Comment by berezovskyi** [comment]
Dear Stefan, thank you for bringing this to our attention. Indeed, the NOTICES file went a bit outdated, my proposed change in #398 should fix the problem you report. /Andrew

**Comment by stefan-hdt** [comment]
Thanks, Andrew.
