### ISSUE TITLE
JEEFormAuthenticator requires 'readEntity' before close

### ISSUE THREAD

**Issue by dhakehurst** [eclipse/lyo#49]
I'm using JEEFormAuthenticator to authenticate against a jazz server.

using:
```
"org.eclipse.lyo.clients:oslc4j-client:4.0.0.M1"
"org.glassfish.jersey.connectors:jersey-apache-connector:2.28"
"org.glassfish.jersey.inject:jersey-hk2:2.28"
```
when trying to authenticate it gets the following exception in ```JEEFormAuthenticator.filter```
```
javax.ws.rs.ProcessingException: Error closing message content input stream.
...
Caused by: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
```

if I modify JEEFormAuthenticator to include ```authResponse.readEntity(String.class)``` before each call to authRespons.close() (also in the followRedirects method).

all seems to work ok.

**Comment by berezovskyi** [comment]
Ah, I missed your bug report earlier, sorry. I have fixed this in https://github.com/eclipse/lyo/commit/d8e2e4bc13e18ffad72af1ffa09bdd7cff0f86da but if you have a better fix, I am glad to review and merge a PR.

**Comment by berezovskyi** [comment]
Let's reopen this if it needs further fixing
