### ISSUE TITLE
Support additional request headers in OslcQuery

### ISSUE THREAD

**Issue by jhemm2** [eclipse/lyo#527]
The current implementation of the OSLCQuery is not designed to allow additional request headers.
In some cases, RDNG requires an additional header, for example the "DoorsRP-Request-Type" Header when querying folders or artifact templates.

As of now this can only be achieved using reflection to update the queryResource field.

Proposed solution(s):
- New field of type Map<String,String> to add headers while creating the OSLCQuery
- Overload OslcQuery#submit  and adapt OslcQuery#getResponse to allow additional headers
- Extend OslcQueryParameters for additional headers.

**Comment by berezovskyi** [comment]
@Jad-el-khoury what do you think?

**Comment by Jad-el-khoury** [comment]
I guess any of the solutions make sense. I prefer the first one.
Any chance you can do a PR @jhemm2 ?
