### ISSUE TITLE
Improve the central readme file to reflect the content within the repo

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo#65]
THere are readme files under store, trs-server, etc. These should be visible from the front readme file somehow.

**Comment by berezovskyi** [comment]
I had to make commits like https://github.com/eclipse/lyo.core/commit/e963a12a3e3fa14389e499cf688eb3f325784944 for merging repos. I think we can first revert those commits and then the README will be right where you expect it to be.

**Comment by jadelkhoury** [comment]
Not sure what that commit does. But I don’t think it’s something that can be automated. 
i was thinking to manually create the front readme file to explain each Of the components of the repo. 
(I’m happy to do this.)

**Comment by berezovskyi** [comment]
Should be done already
