### ISSUE TITLE
Missing project form the domain models

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo#66]
under https://github.com/eclipse/lyo/tree/master/domains/org.eclipse.lyo.tools.domainmodels, we lost the .project file!

**Comment by jadelkhoury** [comment]
@berezovskyi We need to fix thsi before we release, right?

**Comment by berezovskyi** [comment]
not unless you want to regenerate domains POJOs with LyoD 4.0.0.RELEASE before we push the final 4.0.0 domains POJO to maven

**Comment by berezovskyi** [comment]
thanks for the fix
